### ISSUE TITLE
控制台出现异常 java.io.IOException: Invalid marker: 89

### ISSUE THREAD

**Issue by StudyPlay** [yanzhenjie/Durban#5]
`
W/ExifInterface: Invalid image.
                                                                        java.io.IOException: Invalid marker: 89
                                                                            at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1607)
                                                                            at android.media.ExifInterface.loadAttributes(ExifInterface.java:1336)
                                                                            at android.media.ExifInterface.<init>(ExifInterface.java:1053)
                                                                            at com.yanzhenjie.durban.task.BitmapCropTask.crop(BitmapCropTask.java:204)
                                                                            at com.yanzhenjie.durban.task.BitmapCropTask.doInBackground(BitmapCropTask.java:122)
                                                                            at com.yanzhenjie.durban.task.BitmapCropTask.doInBackground(BitmapCropTask.java:43)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
`

**Comment by yanzhenjie** [comment]
收到，我会尽快排查修复。

**Comment by imknown** [comment]
See https://github.com/square/picasso/issues/1504
